config/routes.rb
StoryRev::Application.routes.draw do

  root :to => "pages#store"

  resources :books

  get "shopping_cart" => "orders#view_cart"
  put "shopping_cart" => "orders#update_cart"
  get "update_cart" => "orders#update_cart"

  get "order/step-:step" => "orders#show_step", step: /[1-4]/, as: "order_step"
  post "order/step-:step" => "orders#submit_step", step: /[1-3]/
  post "order/confirmation" => "orders#confirmation"
  get "order/cancel" => "orders#cancel_order"

  get "about" => "pages#about"
  get "help" => "pages#help"

  post "subscribe" => "pages#subscribe"

  # Story hour routes
  namespace :story_hour, path: "story-hour" do
    root :to => "pages#events"

    get "old" => "pages#old"
    get "about" => "pages#about"
  end

  # Admin routes
  namespace :admin do
    root :to => "books#search"

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    post "login" => "sessions#create"

    get "priorities" => "pages#priorities", :as => "priorities"
    get "finances_config" => "pages#finances_config", :as => "finances_config"

    post "toggle_store_open" => "store_open#toggle"

    resources :books do
      resources :editions do
        resources :copies
      end
      collection do
        get 'amazon_info'
        get 'search'
      end
    end

    post "stock_taking/add_copy" => "stock_taking#add_copy"
    delete "stock_taking/remove_copy" => "stock_taking#remove_copy"
    delete "stock_taking" => "stock_taking#clear", :as => "clear_stocks"

    resources :orders do
      resources :order_copies
      resources :extra_costs
      collection do
        get 'pending'
      end
    end
    resources :customers
    resources :copies
    resources :new_copies
    resources :cover_images
    resources :authors
    resources :illustrators
    resources :publishers
    resources :book_types
    resources :formats
    resources :countries
    resources :languages
    resources :collections do
      resources :books, :controller => "collection_books"
    end
    resources :award_types do
      resources :awards
    end
    resources :roles
    post "set_discount_percentage" => "roles#set_discount_percentage"
    resources :transactions do
      collection do
        get 'summarised'
        get 'graph_data'
      end
    end
    resources :transaction_categories
    resources :payment_methods
    resources :accounts
    resources :default_cost_prices
    post "set_default_cost_price" => "default_cost_prices#set_default"
    resources :default_percentages
    post "set_default_percentage" => "default_percentages#set_default"
    resources :loans
  end

  # 404 errors
  if Rails.application.config.show_error_pages
    match '*not_found', to: 'errors#error_404'
  end
end

app/views/admin/pages/finances_config.html.erb
<% content_for :top_nav do %>
  <li>
    <%= link_to "Summary", summarised_admin_transactions_path %>
  </li>
  
  <li>
    <%= link_to "Details", admin_transactions_path %>
  </li>

  <li>
    <%= link_to "Loans", admin_loans_path %>
  </li>
  
  <li class="current">
    <%= link_to "Configure", admin_finances_config_path %>
  </li>
<% end %>

<h2>Transaction Categories</h2>
<ul class="data-list">
  <% @transaction_categories.each do |x| %>
    <li>
      <%= x.name %>
      <%= link_to "Rename", edit_admin_transaction_category_path(x), :class=>"manage-link" %>
      <%= link_to "Remove", admin_transaction_category_path(x), :confirm => "Are you sure you want to delete this item?", :method => "Delete", :class=>"manage-link" %>
    </li>
  <% end %>
    <li class="add"><%= link_to "Add", new_admin_transaction_category_path %></li>
</ul>

<h2>Payment Methods</h2>
<ul class="data-list">
  <% @payment_methods.each do |x| %>
    <li>
      <%= x.name %>
      <%= link_to "Rename", edit_admin_payment_method_path(x), :class=>"manage-link" %>
      <% unless (x.id <= 3) %>
        <%= link_to "Remove", admin_payment_method_path(x), :confirm => "Are you sure you want to delete this item?", :method => "Delete", :class=>"manage-link" %>
      <% end %>
    </li>
  <% end %>
    <li class="add"><%= link_to "Add", new_admin_payment_method_path %></li>
</ul>

<h2>Accounts</h2>
<ul class="data-list">
  <% @accounts.each do |x| %>
    <li>
      <%= x.name %> &ndash; <em><%= x.share %>% profit share</em>
      <%= link_to "Rename", edit_admin_account_path(x), :class=>"manage-link" %>
      <%= link_to "Remove", admin_account_path(x), :confirm => "Are you sure you want to delete this item?", :method => "Delete", :class=>"manage-link" %>
    <li>
  <% end %>
  <li class="add"><%= link_to "Add", new_admin_account_path %></li>
</ul>

app/views/admin/pages/name_form.html.erb
<% content_for :top_nav do %>
  <li>
    <%= link_to "Summary", summarised_admin_transactions_path %>
  </li>
  
  <li>
    <%= link_to "Details", admin_transactions_path %>
  </li>
  
  <li class="current">
    <%= link_to "Configure", admin_finances_config_path %>
  </li>
<% end %>

<%= simple_form_for [:admin, @item], :defaults => { :required => false, :error => false } do |f| %>
  <%= f.input :name %>
  <%= f.submit "Save", :class => "submit" %>
<% end %>

app/views/admin/pages/priorities.html.erb
<% content_for :top_nav do %>
  <li>
    <%= link_to "Collections", admin_collections_path %>
  </li>

  <% if admin? %>
    <li>
      <%= link_to "Configure", admin_roles_path %>
    </li>
  <% end %>

  <li class="current">
    <%= link_to "Priorites", admin_priorities_path %>
  </li>

  <li>
    <%= link_to "Default Cost Prices", admin_default_cost_prices_path %>
  </li>
<% end %>

<div class="column">
  <h2>Collections</h2>
  <ul class="collections">
    <% @collections.each do |x| %>
      <li data-id="<%= x.id %>" data-name="<%= x.name %>" data-priority="<%= x.priority %>">
        <%= x.priority %> - <%= x.name %> <%= link_to "[change]", "#", :class => "change-link" %>
      </li>
    <% end %>
  </ul>

  <h2>Categories</h2>
  <ul class="book_types">
    <% @book_types.each do |x| %>
      <li data-id="<%= x.id %>" data-name="<%= x.name %>" data-priority="<%= x.priority %>">
        <%= x.priority %> - <%= x.name %> <%= link_to "[change]", "#", :class => "change-link" %>
      </li>
    <% end %>
  </ul>

  <h2>Awards</h2>
  <ul class="award_types">
    <% @awards.each do |x| %>
      <li data-id="<%= x.id %>" data-name="<%= x.name %>" data-priority="<%= x.priority %>">
        <%= x.priority %> - <%= x.name %>  <%= link_to "[change]", "#", :class => "change-link" %>
      </li>
    <% end %>
  </ul>

  <h2>Illustrators</h2>
  <ul class="illustrators">
    <% @illustrators.each do |x| %>
      <li data-id="<%= x.id %>" data-name="<%= x.name %>" data-priority="<%= x.priority %>">
        <%= x.priority %> - <%= x.name %>  <%= link_to "[change]", "#", :class => "change-link" %>
      </li>
    <% end %>
  </ul>

  <h2>Publishers</h2>
  <ul class="publishers">
    <% @publishers.each do |x| %>
      <li data-id="<%= x.id %>" data-name="<%= x.name %>" data-priority="<%= x.priority %>">
        <%= x.priority %> - <%= x.name %>  <%= link_to "[change]", "#", :class => "change-link" %>
      </li>
    <% end %>
  </ul>
</div>

<div class="column">
  <h2>Authors</h2>
  <ul class="authors">
    <% @authors.each do |x| %>
      <li data-id="<%= x.id %>" data-name="<%= x.name %>" data-priority="<%= x.priority %>">
        <%= x.priority %> - <%= x.name %>  <%= link_to "[change]", "#", :class => "change-link" %>
      </li>
    <% end %>
  </ul>
</div>