config/routes.rb
StoryRev::Application.routes.draw do

  root :to => "pages#store"

  resources :books

  get "shopping_cart" => "orders#view_cart"
  put "shopping_cart" => "orders#update_cart"
  get "update_cart" => "orders#update_cart"

  get "order/step-:step" => "orders#show_step", step: /[1-4]/, as: "order_step"
  post "order/step-:step" => "orders#submit_step", step: /[1-3]/
  post "order/confirmation" => "orders#confirmation"
  get "order/cancel" => "orders#cancel_order"

  get "about" => "pages#about"
  get "help" => "pages#help"

  post "subscribe" => "pages#subscribe"

  # Story hour routes
  namespace :story_hour, path: "story-hour" do
    root :to => "pages#events"

    get "old" => "pages#old"
    get "about" => "pages#about"
  end

  # Admin routes
  namespace :admin do
    root :to => "books#search"

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    post "login" => "sessions#create"

    get "priorities" => "pages#priorities", :as => "priorities"
    get "finances_config" => "pages#finances_config", :as => "finances_config"

    post "toggle_store_open" => "store_open#toggle"

    resources :books do
      resources :editions do
        resources :copies
      end
      collection do
        get 'amazon_info'
        get 'search'
      end
    end

    post "stock_taking/add_copy" => "stock_taking#add_copy"
    delete "stock_taking/remove_copy" => "stock_taking#remove_copy"
    delete "stock_taking" => "stock_taking#clear", :as => "clear_stocks"

    resources :orders do
      resources :order_copies
      resources :extra_costs
      collection do
        get 'pending'
      end
    end
    resources :customers
    resources :copies
    resources :new_copies
    resources :cover_images
    resources :authors
    resources :illustrators
    resources :publishers
    resources :book_types
    resources :formats
    resources :countries
    resources :languages
    resources :collections do
      resources :books, :controller => "collection_books"
    end
    resources :award_types do
      resources :awards
    end
    resources :roles
    post "set_discount_percentage" => "roles#set_discount_percentage"
    resources :transactions do
      collection do
        get 'summarised'
        get 'graph_data'
      end
    end
    resources :transaction_categories
    resources :payment_methods
    resources :accounts
    resources :default_cost_prices
    post "set_default_cost_price" => "default_cost_prices#set_default"
    resources :default_percentages
    post "set_default_percentage" => "default_percentages#set_default"
    resources :loans
  end

  # 404 errors
  if Rails.application.config.show_error_pages
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  default_scope -> { where(complete: false) }
  attr_accessible :add_copy, :remove_copy, :empty, :change_number

  has_many :order_copies, dependent: :destroy, validate: true
  has_many :copies, through: :order_copies
  has_many :used_copies, through: :order_copies
  has_many :new_copies, through: :order_copies
  has_one :customer, dependent: :destroy

  validates :total_amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :postage_amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :complete, inclusion: { in: [true, false] }

  def self.clear_old(silent = false)
    cleared = 0
    Order.where{updated_at < 14.days.ago}.each do |x|
      x.destroy
      cleared += 1
    end

    puts "Cleared #{cleared} orders" unless silent
  end

  def number_of_items
    copies.length
  end

  def add_copy=(copy_id)
    self.order_copies.create(copy_id: copy_id) unless copy_ids.include? copy_id.to_i
  end

  def remove_copy=(copy_id)
    self.order_copies.where(copy_id: copy_id).each { |oc| oc.destroy }
  end

  def empty=(val)
    self.order_copies.clear if val
  end

  def change_number=(params)
    oc = self.order_copies.find_by_copy_id!(params['copy_id'])
    oc.update_attributes(number: params['number']) if oc
  end

  def cart_amount
    order_copies.inject(0){ |s, x| s + x.price }
  end

  def calculate_amounts
    if customer.delivery_method == 1
      self.postage_amount = order_copies.finalized.inject(30){ |s, x| s + 10 * x.number }
    else
      self.postage_amount = 0
    end

    self.total_amount = order_copies.finalized.inject(0){ |s, x| s + x.price } + postage_amount
  end

  def check_unstocked
    order_copies.each do |x|
      x.final = (x.copy.stock > 0)
      x.save
    end
  end

  def finalize
    raise "Attempted to finalize an order that is already complete" if complete

    customer.step = 4
    raise "Invalid order information" if customer.invalid?

    # Destroy any order copies that were previously shown as being unstocked
    self.order_copies.unfinalized.each{ |x| x.destroy }

    # Check for newly unstocked copies
    check_unstocked

    # Set the stocks for the finalized copies
    self.order_copies.finalized.each{ |x| x.finalize }

    # Set the discount on the order
    self.discount_percentage = ConfigData.access.discount_percentage

    calculate_amounts

    self.complete = true
    self.confirmed_date = DateTime.now
    save
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def pending
    @title = "Pending Orders"
    @class = "orders pending"
    
    @orders = CompleteOrder.includes{[order_copies, customer]}.unfinalized.order_by_confirmed
  end
  
  def index
    @title = "Old Orders"
    @class = "orders old"
    
    @orders = CompleteOrder.includes{[order_copies, customer]}.finalized.order_by_confirmed
  end
  
  def show
    @order = CompleteOrder.find(params[:id])
    
    render json: present(@order).as_hash
  end
  
  def update
    @order = CompleteOrder.find(params[:id])
    
    if @order.update_attributes(params[:order])
      render json: present(@order).as_hash
    else
      render json: @order.errors.full_messages, status: :unprocessable_entity
    end
  end
  
  def destroy
    @order = CompleteOrder.find(params[:id])
    @order.destroy
    render json: { success: true }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :check_order, only: [:show_step, :submit_step, :confirmation]

  def view_cart
    @class = "store shopping-cart"
    @title = "Shopping Cart"

    @order_copies = order.order_copies.order{[(copy.stock < 1), updated_at.desc]}

    respond_to do |format|
      format.html do
        if ConfigData.access.store_open
          render layout: "ajax" if request.xhr?
        else
          render 'view_cart_closed'
        end
      end
      format.json do
       render json: {
          item_count: order.number_of_items,
          total: order.cart_amount,
          html: params[:get_html] ? render_to_string(formats: :html, layout: "ajax") : nil
        }
      end
    end
  end

  def update_cart
    store_order if order.new_record?

    unless ConfigData.access.store_open
      # Skip updating the order since the store is closed
      respond_to do |format|
        format.html { redirect_to shopping_cart_path }
        format.json { redirect_to action: :view_cart, get_html: params[:get_html], format: :json }
      end
      return
    end

    if order.update_attributes(params[:order])
      respond_to do |format|
        format.html { redirect_to shopping_cart_path }
        format.json { redirect_to action: :view_cart, get_html: params[:get_html], format: :json }
      end
    else
      raise "Shopping cart update failed"
    end
  end

  def show_step
    unless ConfigData.access.store_open
      # Show shopping cart since the store is closed
      redirect_to shopping_cart_path
      return
    end

    return unless get_customer_and_set_step
    @customer.set_defaults

    # Calculate the order amounts and check unstocked copies if we're on the final step
    if @step == 4
      order.check_unstocked
      order.calculate_amounts
    end

    render layout: "ajax" if request.xhr?
  end

  def submit_step
    return unless get_customer_and_set_step

    if @customer.update_attributes(params[:customer])
      redirect_to order_step_path(step: @step + 1)
    else
      render "show_step", layout: request.xhr? ? "ajax" : true
    end
  end

  def confirmation
    @confirmed_order = order
    session.delete(:order_id)
    @confirmed_order.finalize

    OrderMailer.delay.confirmation(@confirmed_order)
    OrderMailer.delay.notify_owner(@confirmed_order)

    render layout: "ajax" if request.xhr?
  end

  def cancel_order
    order.customer.destroy if order.customer.present?
    if request.xhr?
      render json: { success: true }
    else
      redirect_to root_path(show_cart: true)
    end
  end

  private

  def check_order
    if order.order_copies.stocked.length == 0
      num = order.number_of_items
      if num > 0
        message = "We're very sorry, but someone else has ordered the #{num > 1 ? 'items' : 'item'} in your shopping cart, and #{num > 1 ? 'they are' : 'it is'} now unavailable."
      else
        message = "Your shopping cart is empty, so an order cannot be placed."
      end

      if request.xhr?
        render :text => message, :status => 400
      else
        redirect_to shopping_cart_path, :notice => message
      end
    end
  end

  def get_customer_and_set_step
    @step = params[:step].to_i
    @customer = order.customer || order.build_customer
    @customer.step = @step

    # If the step was invalid redirect to the last valid step
    if @customer.step == @step
      return true
    else
      redirect_to order_step_path(step: @customer.step)
      return false
    end
  end
end

app/views/admin/orders/_view_and_edit.html.erb
<div class="table-container">
  <table id="orders-table" data-init-select="<%= params[:selected_id] %>">
    <% @orders.each do |order| %>
      <% present(order) do |o| %>
        <tr data-id="<%= o.number %>">
          <td class="date" data-sort-by="<%= o.timestamp %>"><%= o.formatted_date %>
          <td data-sort-by="<%= o.number %>"><%= o.number %></td>
          <td data-sort-by="<%= o.name %>"><%= o.name %></td>
          <td data-sort-by="<%= o.city %>"><%= o.city %></td>
          <td data-sort-by="<%= o.delivery_short %>"><%= o.delivery_short %></td>
          <td data-sort-by="<%= o.number_of_copies %>"><%= o.number_of_copies %> books</td>
          <td class="total" data-sort-by="<%= o.total_amount %>"><%= o.formatted_total_amount %></td>
          <td class="paid"><%= o.paid_check_box %></td>
          <td class="posted"><%= o.posted_check_box %></td>
          <td class="has-button"><%= o.edit_link("") %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

<section id="order-info">
  <h2>Order : <span class="name"></span></h2>
  
  <div class="amount">
    <p class="postage">Postage: <span></span></p>
    <p class="total">Total: <span></span></p>
    <p class="discount">Discount: <span></span></p>
    <p class="postage-expenditure">Postage expenditure: <span></span><a href="#" class="edit-link"></a>
    </p>
  </div>
  
  <div class="table-wrapper" id="order-copies">
    <p class="note">Note: prices for each copy below are before the discount has been applied</p>
    <div class="table-container">
      <table></table>
    </div>
    <p class="add-container"><a href="#" class="add-link">Manually add book</a></p>
  </div>

  <div class="table-wrapper" id="order-costs">
    <div class="table-container">
      <table></table>
    </div>
  </div>
  
  <div class="info">
    <p class="email" title="Email"></p>
    
    <div class="address" title="Address">
      <span class="icon"></span>
      <pre></pre>
    </div>
    
    <p class="phone" title="Phone"></p>
    
    <p class="payment"></p>
    
    <p class="delivery"></p>
    <p class="pickup"></p>
  </div>
  
  <div class="comments" title="Comments">
    <pre></pre>
    <a href="#" class="edit-link"></a>
  </div>
  
  <div class="notes" title="Notes">
    <pre></pre>
    <a href="#" class="edit-link"></a>
  </div>
</section>

app/views/admin/orders/index.html.erb
<% content_for :top_nav do %>
  <li>
    <%= link_to "Pending Orders", pending_admin_orders_path %>
  </li>
  
  <li class="current">
    <%= link_to "Old Orders", admin_orders_path %>
  </li>
  
  <li>
    <%= link_to "Add Order", new_admin_customer_path %>
  </li>
<% end %>

<%= render "view_and_edit" %>

app/views/admin/orders/new.html.erb
<% content_for :top_nav do %>
  <li>
    <%= link_to "Pending Orders", pending_admin_orders_path %>
  </li>
  
  <li>
    <%= link_to "Old Orders", admin_orders_path %>
  </li>
  
  <li class="current">
    <%= link_to "Add Order", new_admin_order_path %>
  </li>
<% end %>

<%= render "fields" %>

app/views/admin/orders/pending.html.erb
<% content_for :top_nav do %>
  <li class="current">
    <%= link_to "Pending Orders", pending_admin_orders_path %>
  </li>
  
  <li>
    <%= link_to "Old Orders", admin_orders_path %>
  </li>
  
  <li>
    <%= link_to "Add Order", new_admin_customer_path %>
  </li>
<% end %>

<%= render "view_and_edit" %>