config/routes.rb
StoryRev::Application.routes.draw do

  root :to => "pages#store"

  resources :books

  get "shopping_cart" => "orders#view_cart"
  put "shopping_cart" => "orders#update_cart"
  get "update_cart" => "orders#update_cart"

  get "order/step-:step" => "orders#show_step", step: /[1-4]/, as: "order_step"
  post "order/step-:step" => "orders#submit_step", step: /[1-3]/
  post "order/confirmation" => "orders#confirmation"
  get "order/cancel" => "orders#cancel_order"

  get "about" => "pages#about"
  get "help" => "pages#help"

  post "subscribe" => "pages#subscribe"

  # Story hour routes
  namespace :story_hour, path: "story-hour" do
    root :to => "pages#events"

    get "old" => "pages#old"
    get "about" => "pages#about"
  end

  # Admin routes
  namespace :admin do
    root :to => "books#search"

    get "logout" => "sessions#destroy", :as => "logout"
    get "login" => "sessions#new", :as => "login"
    post "login" => "sessions#create"

    get "priorities" => "pages#priorities", :as => "priorities"
    get "finances_config" => "pages#finances_config", :as => "finances_config"

    post "toggle_store_open" => "store_open#toggle"

    resources :books do
      resources :editions do
        resources :copies
      end
      collection do
        get 'amazon_info'
        get 'search'
      end
    end

    post "stock_taking/add_copy" => "stock_taking#add_copy"
    delete "stock_taking/remove_copy" => "stock_taking#remove_copy"
    delete "stock_taking" => "stock_taking#clear", :as => "clear_stocks"

    resources :orders do
      resources :order_copies
      resources :extra_costs
      collection do
        get 'pending'
      end
    end
    resources :customers
    resources :copies
    resources :new_copies
    resources :cover_images
    resources :authors
    resources :illustrators
    resources :publishers
    resources :book_types
    resources :formats
    resources :countries
    resources :languages
    resources :collections do
      resources :books, :controller => "collection_books"
    end
    resources :award_types do
      resources :awards
    end
    resources :roles
    post "set_discount_percentage" => "roles#set_discount_percentage"
    resources :transactions do
      collection do
        get 'summarised'
        get 'graph_data'
      end
    end
    resources :transaction_categories
    resources :payment_methods
    resources :accounts
    resources :default_cost_prices
    post "set_default_cost_price" => "default_cost_prices#set_default"
    resources :default_percentages
    post "set_default_percentage" => "default_percentages#set_default"
    resources :loans
  end

  # 404 errors
  if Rails.application.config.show_error_pages
    match '*not_found', to: 'errors#error_404'
  end
end

app/models/admin/role.rb
class Admin::Role < ActiveRecord::Base
  self.table_name = :admin_roles
  
  attr_accessible :password, :password_confirmation, :admin_password
  attr_accessor :password, :admin_password
  attr_writer :admin_password
  before_save :encrypt_password
  
  validates :password, presence: true, confirmation: true
  validates :admin_password, admin: true
  validates :name, presence: true, length: { maximum: 100 }
  
  def self.authenticate(password)
    self.all.each do |r|
      if r.password_hash == BCrypt::Engine.hash_secret(password, r.password_salt)
        return r.name
      end
    end
    return nil
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::ApplicationController
  before_filter :require_admin
  
  def index
    @class = "passwords"
    @title = "Passwords"
    @roles = Admin::Role.order(:created_at)
    @discount_percentage = ConfigData.access.discount_percentage
  end
  
  def update
    @role = Admin::Role.find(params[:id])
    if @role.update_attributes(params[:admin_role])
      redirect_to admin_roles_path, :notice => "The #{@role.name} password has been changed."
    else
      redirect_to admin_roles_path, :notice => "Invalid password."
    end
  end

  def set_discount_percentage
    config = ConfigData.access
    config.discount_percentage = params[:discount_percentage]
    if config.save
      redirect_to admin_roles_path, notice: "The store-wide discount percentage has been changed"
    else
      redirect_to admin_roles_path, alert: "Invalid entry"
    end
  end
end

app/views/admin/roles/index.html.erb
<% content_for :top_nav do %>
  <li>
    <%= link_to "Collections", admin_collections_path %>
  </li>

  <% if admin? %>
    <li class="current">
      <%= link_to "Configure", admin_roles_path %>
    </li>
  <% end %>

  <li>
    <%= link_to "Priorites", admin_priorities_path %>
  </li>

  <li>
    <%= link_to "Default Cost Prices", admin_default_cost_prices_path %>
  </li>
<% end %>

<div class="discount-percentage">
  <h2>Store-wide discount percentage</h2>
  <%= form_tag admin_set_discount_percentage_path, method: :post do %>
    <%= text_field_tag :discount_percentage, @discount_percentage, size: 2 %>
    <%= submit_tag "Set" %>
  <% end %>
</div>

<div class="store-open">
  <p><strong>The store is currently <%= ConfigData.access.store_open ? 'open' : 'closed' %></strong></p>

  <p><%= link_to (ConfigData.access.store_open ? 'Close store' : 'Open store'), admin_toggle_store_open_path, method: :post %></p>
</div>

<p>Change passwords:</p>
<ul class="roles">
  <% @roles.each do |r| %>
    <li><%= link_to r.name, "#", "data-id" => r.id %></li>
  <% end %>
</ul>

<% @roles.each do |r| %>
  <div class="role-form" id="role-<%= r.id %>">
    <%= simple_form_for r, :defaults => { :required => false, :error => false } do |f| %>
      <%= f.input :admin_password, :label_html => { :class => "multi-line" }, :label => "Current admin password" %>
      <%= f.input :password, :label_html => { :class => "multi-line" }, :label => "New #{r.name} password" %>
      <%= f.input :password_confirmation, :label_html => { :class => "multi-line" }, :label => "Re-enter new #{r.name} password" %>
      <%= f.submit "Save", :class => "submit" %>
    <% end %>
  </div>
<% end %>